spring:
  datasource:
    password: t5y6u7i8
    url: jdbc:postgresql://localhost:5432/dscatalog
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
